### ISSUE TITLE
JDOM 2 exception with version 1.1.17

### ISSUE THREAD

**Issue by michelesalvador** [geonames/webservice-client#6]
In an Android app I added the dependency:
```
implementation 'org.geonames:geonames-ws-client:1.1.17'
```
I run this code:
```
lifecycleScope.launch(Dispatchers.IO) {
    WebService.setUserName("demo")
    val searchCriteria = ToponymSearchCriteria()
    searchCriteria.q = "zurich"
    val searchResult = WebService.search(searchCriteria)
    ...
}
```
And I get this exception:
```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: com.example, PID: 15346
org.jdom2.JDOMException: http://xml.org/sax/features/external-general-entities feature http://xml.org/sax/features/external-general-entities not supported for SAX driver org.apache.harmony.xml.ExpatReader
	at org.jdom2.input.SAXBuilder.internalSetFeature(SAXBuilder.java:1011)
	at org.jdom2.input.SAXBuilder.configureParser(SAXBuilder.java:984)
	at org.jdom2.input.SAXBuilder.buildEngine(SAXBuilder.java:859)
	at org.jdom2.input.SAXBuilder.getEngine(SAXBuilder.java:907)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1079)
	at org.geonames.WebService.connectAndParse(WebService.java:289)
	at org.geonames.WebService.search(WebService.java:1192)
	at com.example.MainActivity$onCreate$1$1.invokeSuspend(MainActivity.kt:26)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b61b14d, Dispatchers.IO]
```
Thank you!

**Comment by juherr** [comment]
The default SAX parser on Android doesn't implement all the needed features by JDOM.
See https://github.com/hunterhacker/jdom/wiki/JDOM2-and-Android

The SAXBuilder is created here, and you don't have a way to modify it:
https://github.com/geonames/webservice-client/blob/master/org/geonames/WebService.java#L301

I don't know if you can tell JDOM to use another SAX parser from the outside.
